### ISSUE TITLE
Linking and Importing Projects

### ISSUE THREAD

**Issue by NyanKiyoshi** [NyanKiyoshi/auto-stack-documenter#3]
Using a go-modules-like mechanism, we would like to be able to define the sources, meaning having a file inspired from `go.mod` as `docs.ini`:

```yaml
# The name of the documentation
module: github.com/NyanKiyoshi/my-stack-auto-docs

# Any git DVCS, including private repositories requiring a secret key.
#
# All of them will get cloned using `ssh` at build time by the CI or maintainer,
# meaning those keys will never be passed or stored by the tool itself.
requires:
  - github.com/stack-docs/main-things       # Contains mixed content, such as Go, Python, k8s files, etc.
  - github.com/stack-docs/library-golang    # A Go library used among other repositories in the stack
```

Those will be used to build the stack documentation, and cross-reference.
